/**
 * This JFrame form allows the player to input each Fighter's stats.
 */
package jfighterproject;

import javax.swing.JOptionPane;
public class JFighterInputStats extends javax.swing.JFrame {

    /**
     * Creates new form JFighterInputStats
     */
    public JFighterInputStats() {
        initComponents();
        this.setTitle("Enter Fighter Stats");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonStartGame = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldName1 = new javax.swing.JTextField();
        jTextFieldHealth1 = new javax.swing.JTextField();
        jTextFieldArmor1 = new javax.swing.JTextField();
        jTextFieldDice1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldName2 = new javax.swing.JTextField();
        jTextFieldHealth2 = new javax.swing.JTextField();
        jTextFieldArmor2 = new javax.swing.JTextField();
        jTextFieldDice2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Enter Fighter 1 Stats:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Enter Fighter 2 Stats:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, -1, -1));

        jButtonStartGame.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonStartGame.setText("Start Game");
        jButtonStartGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartGameActionPerformed(evt);
            }
        });
        jButtonStartGame.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonStartGameKeyPressed(evt);
            }
        });
        getContentPane().add(jButtonStartGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 310, 140, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 60, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Health:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 70, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Armor:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 70, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Number of attack dice:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jTextFieldName1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextFieldName1.setText("Fighter 1");
        jTextFieldName1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldName1FocusGained(evt);
            }
        });
        getContentPane().add(jTextFieldName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 210, 40));

        jTextFieldHealth1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextFieldHealth1.setText("10");
        jTextFieldHealth1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldHealth1FocusGained(evt);
            }
        });
        getContentPane().add(jTextFieldHealth1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 80, 40));

        jTextFieldArmor1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextFieldArmor1.setText("3");
        jTextFieldArmor1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldArmor1FocusGained(evt);
            }
        });
        getContentPane().add(jTextFieldArmor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 80, 40));

        jTextFieldDice1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextFieldDice1.setText("5");
        jTextFieldDice1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldDice1FocusGained(evt);
            }
        });
        getContentPane().add(jTextFieldDice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 80, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Name:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Health:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Armor:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Number of attack dice:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, -1, -1));

        jTextFieldName2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextFieldName2.setText("Fighter 2");
        jTextFieldName2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldName2FocusGained(evt);
            }
        });
        getContentPane().add(jTextFieldName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 110, 240, 40));

        jTextFieldHealth2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextFieldHealth2.setText("10");
        jTextFieldHealth2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldHealth2FocusGained(evt);
            }
        });
        getContentPane().add(jTextFieldHealth2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 160, 80, 40));

        jTextFieldArmor2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextFieldArmor2.setText("3");
        jTextFieldArmor2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldArmor2FocusGained(evt);
            }
        });
        getContentPane().add(jTextFieldArmor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 210, 80, 40));

        jTextFieldDice2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextFieldDice2.setText("5");
        jTextFieldDice2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldDice2FocusGained(evt);
            }
        });
        getContentPane().add(jTextFieldDice2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 260, 80, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Creates an instance of JFighterProject with 2 Fighters with stats that
     * the player entered on this Form.
     */
    private void startGame() {
        boolean isInputOk = true;
        int health1 = 0;
        int armor1 = 0;
        int dice1 = 0;
        
        int health2 = 0;
        int armor2 = 0;
        int dice2 = 0;
        
        /**
         * Create two Fighters from the information from the player.
         * If any numeric field is not a number, do not start the game.
         * Instead, display an error message and have the player enter values again.
         */
        try {
            health1 = Integer.parseInt(this.jTextFieldHealth1.getText());
            armor1 = Integer.parseInt(this.jTextFieldArmor1.getText());
            dice1 = Integer.parseInt(this.jTextFieldDice1.getText());

            health2 = Integer.parseInt(this.jTextFieldHealth2.getText());
            armor2 = Integer.parseInt(this.jTextFieldArmor2.getText());
            dice2 = Integer.parseInt(this.jTextFieldDice2.getText());
        }
        catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(rootPane, "Health, armor, and/or dice must be numbers.");
            isInputOk = false;
        }
        
        // start the game once the input is valid
        if (isInputOk) {
            Fighter fighter1 = new Fighter(this.jTextFieldName1.getText(), health1, armor1, dice1);
            Fighter fighter2 = new Fighter(this.jTextFieldName2.getText(), health2, armor2, dice2);
            
            // instantiate the actual game Form.
            JFighterProject jfp = new JFighterProject(fighter1, fighter2);
            jfp.setVisible(true);
            this.setVisible(false);
        }
    }
    
    /**
     * This starts the game once the user clicks on the "Start Game" button
     * @param evt
     */
    private void jButtonStartGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartGameActionPerformed
        // TODO add your handling code here:
        this.startGame();
    }//GEN-LAST:event_jButtonStartGameActionPerformed

    // These event handlers select text from the input fields when the user
    // clicks or tabs over to them
    private void jTextFieldName1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldName1FocusGained
        // TODO add your handling code here:
        this.jTextFieldName1.selectAll();
    }//GEN-LAST:event_jTextFieldName1FocusGained

    private void jTextFieldHealth1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldHealth1FocusGained
        // TODO add your handling code here:
        this.jTextFieldHealth1.selectAll();
    }//GEN-LAST:event_jTextFieldHealth1FocusGained

    private void jTextFieldArmor1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldArmor1FocusGained
        // TODO add your handling code here:
        this.jTextFieldArmor1.selectAll();
    }//GEN-LAST:event_jTextFieldArmor1FocusGained

    private void jTextFieldDice1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDice1FocusGained
        // TODO add your handling code here:
        this.jTextFieldDice1.selectAll();
    }//GEN-LAST:event_jTextFieldDice1FocusGained

    private void jTextFieldName2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldName2FocusGained
        // TODO add your handling code here:
        this.jTextFieldName2.selectAll();
    }//GEN-LAST:event_jTextFieldName2FocusGained

    private void jTextFieldHealth2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldHealth2FocusGained
        // TODO add your handling code here:
        this.jTextFieldHealth2.selectAll();
    }//GEN-LAST:event_jTextFieldHealth2FocusGained

    private void jTextFieldArmor2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldArmor2FocusGained
        // TODO add your handling code here:
        this.jTextFieldArmor2.selectAll();
    }//GEN-LAST:event_jTextFieldArmor2FocusGained

    private void jTextFieldDice2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDice2FocusGained
        // TODO add your handling code here:
        this.jTextFieldDice2.selectAll();
    }//GEN-LAST:event_jTextFieldDice2FocusGained

    /**
     * This allows the player to press the enter key to activate the "Start Game"
     * button
     * @param evt the KeyEvent containing the KeyCode of the key pressed.
     */
    private void jButtonStartGameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonStartGameKeyPressed
       // KeyCode of 10 is the Enter key
       if (evt.getKeyCode() == 10) {
           this.startGame();
       }
    }//GEN-LAST:event_jButtonStartGameKeyPressed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFighterInputStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFighterInputStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFighterInputStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFighterInputStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFighterInputStats().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonStartGame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextFieldArmor1;
    private javax.swing.JTextField jTextFieldArmor2;
    private javax.swing.JTextField jTextFieldDice1;
    private javax.swing.JTextField jTextFieldDice2;
    private javax.swing.JTextField jTextFieldHealth1;
    private javax.swing.JTextField jTextFieldHealth2;
    private javax.swing.JTextField jTextFieldName1;
    private javax.swing.JTextField jTextFieldName2;
    // End of variables declaration//GEN-END:variables
}
